name: TechTrends - Package with Docker

on: 
  push:
    branches:
      [main]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v2
    - 
      name: Set Up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set Up buildx
      uses: docker/setup-buildx-action@v1
    -
      name: lgoin to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}
    -
      name: Build and Push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64
        push: true
        tags: coralsparrow/techtrends:latest
    